### ISSUE TITLE
test/resigner.c is non-free (and confidential)

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/libksi#1]
test/resigner.c is not FLOSS licensed, but `GUARDTIME CONFIDENTIAL` and distribution is forbidden?

**Comment by rgerhards** [comment]
Thanks, I didn't notice that. I got the libksi from GuardTime with explicit permission to publish it as open source, so I guess it's a bug on their side. But I need to coordiate with them. Depending on the outcome, I'll either update the file or remove it.

**Comment by ahtotruu** [comment]
We just missed this file when preparing the package for release. Pull request sent.

**Comment by andreasstieger** [comment]
https://github.com/rgerhards/libksi/pull/1  was merged, closing.
